export type Language = 'ar' | 'en'

// Ordered longest-first so complete phrases win before individual terms.
const EN: [string, string][] = [
  ['لا تبحث بالنت،', "Don't search online,"], ['ابحث حولك.', 'look around you.'],
  ['في نفس الكوفي، وعلى طاولة قريبة… تلقى اللي تحتاجه.', 'In the same coffee shop, at a nearby table… find what you need.'],
  ['مصمّمة هوية', 'Brand designer'], ['مبرمج', 'Developer'], ['أبحث عن مترجم', 'Looking for a translator'], ['مصوّر', 'Photographer'], ['طاولتك', 'Your table'], ['نفس الكوفي', 'Same coffee shop'], ['يلا نبدأ', 'Get started'],
  ['رقم جوالك', 'Your phone number'], ['عشان يكون كل اللي حولك أشخاص حقيقيين. رقمك ما يظهر لأحد.', 'This helps keep the community real. Your number is never shown to anyone.'], ['رقم الجوال', 'Phone number'], ['أرسل الرمز', 'Send code'], ['اكتب الرمز اللي وصلك', 'Enter the code we sent'], ['أرسلنا رمز التحقق المكوّن من', 'We sent you a verification code with'], ['أرقام.', 'digits.'], ['رمز التحقق', 'Verification code'], ['إعادة الإرسال بعد', 'Resend in'], ['أرسل الرمز مرة ثانية', 'Send the code again'], ['تأكيد الرمز', 'Verify code'],
  ['خلنا نشوف وش حولك', "Let's see what is around you"], ['نستخدم موقعك عشان نوريك الأقرب لك أول. موقعك الدقيق ما يظهر لأي أحد، يظهر بس اسم الكافيه.', 'We use your location to show the closest places first. Your precise location is private; only the coffee shop name is shown.'], ['استخدم موقعي', 'Use my location'], ['أختار المدينة والحي بنفسي', 'Choose city and neighbourhood manually'],
  ['وين أنت؟', 'Where are you?'], ['نرتّب لك الأشخاص والكافيهات من الأقرب لك', 'We sort people and coffee shops by distance'], ['الأدق', 'Most accurate'], ['استخدم موقعي الحالي', 'Use my current location'], ['المدينة', 'City'], ['الحي', 'Neighbourhood'], ['اعتمد الموقع', 'Confirm location'], ['غيّر المدينة', 'Change city'],
  ['الرياض', 'Vancouver, BC'], ['العليا', 'Yaletown'], ['الورود', 'Downtown'], ['السليمانية', 'Mount Pleasant'], ['الملز', 'Kitsilano'], ['جدة', 'Toronto, ON'], ['الدمام', 'Montreal, QC'], ['مكة', 'Calgary, AB'], ['المدينة', 'Ottawa, ON'], ['أبها', 'Victoria, BC'],
  ['مقهى الحطب', 'JJ Bean'], ['مساحة العمل', 'Starbucks Yaletown'], ['مقهى ركن', 'Coco Coffee'], ['حديقة البن', 'Matchstick'],
  ['وش حاب تسوي اليوم؟', 'What would you like to do today?'], ['عندي شيء أبي أنجزه', 'I have something to get done'], ['أحتاج مساعدة', 'I need help'], ['عندي خبرة أقدر أشاركها', 'I have experience to share'], ['أقدر أساعد', 'I can help'], ['التواصل بموافقة الطرفين', 'Both people approve before connecting'], ['ما أحد يقدر يراسلك إلا إذا وافقتوا الاثنين.', 'No one can message you until you both agree.'],
  ['وش تحتاج تنجز اليوم؟', 'What do you need to get done today?'], ['وش تقدر تساعد فيه؟', 'What can you help with?'], ['اكتب احتياجك بشكل بسيط أو اختر من الاقتراحات.', 'Briefly describe what you need, or choose a suggestion.'], ['اختر مهارة أو أكثر، وأضف تفاصيل لو تبي.', 'Choose one or more skills and add details if you like.'], ['مثلاً: أبغى أحد يراجع عرضي التقديمي', 'For example: I need someone to review my presentation'], ['فهمنا:', 'We understood:'], ['تفاصيل إضافية (اختياري): مثلاً أقدر أراجع كود React Native', 'Additional details (optional): for example, I can review React Native code'], ['خصوصيتك محفوظة', 'Your privacy is protected'], ['احتياجك يظهر بدون اسمك وصورتك حتى توافقون الاثنين.', 'Your request stays anonymous until you both agree.'], ['احتياجك يظهر مع اسمك للي حولك، والمحادثة ما تبدأ إلا بموافقتكم.', 'People nearby can see your name, but chat opens only after mutual approval.'], ['مهاراتك تظهر فقط للأشخاص القريبين منك.', 'Only people nearby can see your skills.'], ['اعرض اللي يقدرون يساعدوني', 'Show people who can help me'], ['اعرض اللي يحتاجون مساعدتي', 'Show people who need my help'],
  ['الرئيسية', 'Home'], ['حولك', 'Nearby'], ['الكافيهات', 'Coffee shops'], ['الرسائل', 'Messages'], ['حسابي', 'Account'], ['متواجدون الآن', 'Here now'], ['قادمون اليوم', 'Coming today'], ['الكل', 'All'], ['الآن', 'Now'], ['اليوم', 'Today'], ['ابحث عن شخص أو مهارة أو كافيه', 'Search people, skills, or coffee shops'], ['ما لقينا نتائج', 'No results found'], ['جرّب تغيّر البحث أو الفلتر.', 'Try changing your search or filter.'], ['الأقرب لك', 'Closest to you'], ['افتح الكافيه', 'Open coffee shop'], ['عرض التفاصيل', 'View details'], ['تفاصيل الكافيه', 'Coffee shop details'],
  ['يقدرون يساعدونك هنا', 'People here can help you'], ['يحتاجون مساعدتك هنا', 'People here need your help'], ['يقدرون يساعدون', 'Can help'], ['يحتاجون مساعدة', 'Need help'], ['يقدرون يساعدونك', 'can help you'], ['يحتاجون مساعدتك', 'need your help'], ['ما فيه أحد متاح للمساعدة حاليًا', 'No one is available to help right now'], ['ما فيه احتياجات حاليًا', 'No requests right now'], ['مفتوح الآن', 'Open now'], ['يغلق 11 م', 'Closes at 11 PM'], ['دقائق مشي', 'min walk'], ['دقائق بالسيارة', 'min drive'], ['دقيقة', 'min'], ['دقائق', 'min'],
  ['هادئ للعمل', 'Quiet for work'], ['واي فاي', 'Wi-Fi'], ['مقابس', 'Power outlets'], ['مواقف', 'Parking'], ['جلسات خارجية', 'Patio'], ['غرف اجتماعات', 'Meeting rooms'], ['عند النافذة', 'By the window'], ['الطاولة الطويلة', 'Long table'], ['قريب من الكاونتر', 'Near the counter'], ['الجلسات الخارجية', 'Patio'], ['منطقة الهدوء', 'Quiet area'], ['غرفة الاجتماعات 2', 'Meeting room 2'], ['الحديقة الجانبية', 'Side patio'],
  ['بانتظار الرد', 'Waiting for a reply'], ['مو متاح الحين', 'Not available right now'], ['افتح المحادثة', 'Open chat'], ['أعرض مساعدتي', 'Offer my help'], ['اطلب مساعدته', 'Ask for his help'], ['اطلب مساعدتها', 'Ask for her help'], ['محادثة نشطة', 'Active chat'], ['أنت:', 'You:'], ['تقابلت مع', 'Did you meet'], ['لا، مو بعد', 'Not yet'], ['إيه، تقابلنا', 'Yes, we met'],
  ['مهاراتي واحتياجاتي', 'My skills and needs'], ['اللي يشوفه الناس حولك', 'What people nearby see'], ['نستخدم مهاراتك واحتياجاتك عشان نوريك القريبين المناسبين، والتواصل دايمًا بموافقة الطرفين.', 'We use your skills and needs to find relevant people nearby. Connecting always requires mutual approval.'], ['تظهر للموجودين في الكافيه لما يدورون على أحد يساعدهم في هالمجالات.', 'Shown to people at the coffee shop when they need help in these areas.'], ['ما أضفت مهارات بعد. اكتب مهارة تحت عشان تظهر للي يحتاجونها.', 'You have not added any skills yet. Add one below so people can find you.'], ['اكتب مهارة (مثلاً: Flutter، SEO)', 'Enter a skill (for example: Flutter or SEO)'], ['اقتراحات:', 'Suggestions:'], ['الوقت اللي تقدر تعطيه عادةً', 'Time you can usually offer'], ['حدد المجالات اللي تحتاج فيها مساعدة عادةً، عشان نوريك القريبين اللي عندهم هالخبرة.', 'Choose areas where you usually need help so we can find nearby people with that experience.'], ['وش تحتاج أو تبي تنجز حاليًا؟', 'What do you currently need or want to complete?'], ['مثلاً: أحتاج أحد يراجع معمارية قاعدة بيانات تطبيقي', 'For example: I need someone to review my app database architecture'], ['التواجد والتنبيهات', 'Availability and notifications'], ['متاح للمساعدة', 'Available to help'], ['تظهر في قائمة «يقدرون يساعدون» عند تفعيل هذا الخيار', 'You appear in the Can help list when this is enabled'], ['نبّهني بالمناسبين', 'Notify me about matches'], ['لما يتواجد قريب مني أحد يقدر يساعدني أو يحتاج خبرتي', 'When someone nearby can help me or needs my experience'], ['كيف يشوفك الآخرون', 'How others see you'], ['يحتاج حاليًا:', 'Currently needs:'], ['حفظ التعديلات', 'Save changes'], ['شوف المناسبين حولك', 'See relevant people nearby'],
  ['ملفك في AroundMe', 'Your AroundMe profile'], ['الإعدادات', 'Settings'], ['تعديل الملف الشخصي', 'Edit profile'], ['غير متاح حاليًا', 'Unavailable right now'], ['مرة ساعدت', 'times helped'], ['مرة استفدت', 'times helped me'], ['أماكن زرتها', 'places visited'], ['أماكن حفظتها', 'Saved places'], ['محفوظ', 'Saved'], ['زياراتك الأخيرة', 'Recent visits'], ['كل الكافيهات', 'All coffee shops'], ['أمس', 'Yesterday'], ['قبل 3 أيام', '3 days ago'], ['ساعدت شخصين · استفدت من شخص', 'Helped two people · received help from one'], ['استفدت من مراجعة نموذج مالي', 'Received help reviewing a financial model'],
  ['الخصوصية والتواصل', 'Privacy and communication'], ['إخفاء هويتي قبل الموافقة', 'Hide my identity before approval'], ['ما يظهر اسمك أو صورتك إلا بعد موافقة الطرفين', 'Your name and photo appear only after mutual approval'], ['الإشعارات', 'Notifications'], ['الطلبات والردود والرسائل الجديدة', 'Requests, replies, and new messages'], ['الموقع والظهور', 'Location and visibility'], ['موقعي', 'My location'], ['أتواصل مع نفس الجنس فقط', 'Connect with the same gender only'], ['يظهر لك ويشوفك بس الأشخاص من نفس الجنس', 'Only people of the same gender can see and connect with you'], ['تسجيل الخروج', 'Log out'],
  ['نشطة', 'Active'], ['سابقة', 'Past'], ['ما عندك محادثات الحين', 'You have no active chats'], ['ما فيه محادثات سابقة', 'No past chats'], ['لما توافق أنت وشخص ثاني، تنفتح بينكم محادثة هنا.', 'When you and another person agree, your chat opens here.'], ['المحادثات اللي انتهت تظهر هنا.', 'Completed chats appear here.'], ['شوف مين حولك', 'See who is nearby'], ['رسائل جديدة', 'New messages'], ['أنا جايك', "I'm coming over"], ['وين جالس؟', 'Where are you sitting?'], ['بتأخر شوي', "I'll be a little late"], ['اكتب رسالة', 'Write a message'], ['إرسال', 'Send'], ['رجوع للرسائل', 'Back to messages'], ['انتهت المحادثة، وتقدر تقراها بس.', 'This chat has ended and is now read-only.'], ['تقابلتوا. المحادثة صارت للقراءة بس.', 'You met. This chat is now read-only.'],
  ['عرّفنا عليك', 'Tell us about yourself'], ['مرة وحدة بس، عشان يكون اللقاء واضح وآمن للطرفين', 'Just once, so meetings are clear and safe for both people'], ['اسمك ووظيفتك يظهرون للي توافق تتواصل معهم', 'Your name and role are shown only to people you agree to connect with'], ['غيّر الصورة', 'Change photo'], ['وش اسمك؟', 'What is your name?'], ['وش تشتغل؟', 'What do you do?'], ['مثلاً: مطور واجهات أمامية · الرياض', 'For example: Front-end developer · Vancouver'], ['أنت', 'You are'], ['رجل', 'Man'], ['امرأة', 'Woman'], ['تفضّل تتواصل مع', 'Who would you prefer to connect with?'], ['نفس الجنس فقط', 'Same gender only'], ['التالي', 'Continue'],
  ['اختر مهارة وحدة على الأقل', 'Choose at least one skill'], ['ابحث أو اكتب مهارة', 'Search or enter a skill'], ['إضافة', 'Add'], ['مهارات', 'skills'], ['حفظ ومتابعة', 'Save and continue'], ['تعرض مساعدتك؟', 'Offer your help?'], ['وش تحتاج بالضبط؟', 'What exactly do you need?'], ['كم تقدر تعطي من وقتك؟', 'How much time can you offer?'], ['أرسل الطلب', 'Send request'], ['أرسل العرض', 'Send offer'], ['أرسلنا', 'We sent'], ['نبلغك أول ما يرد. المحادثة تنفتح بس إذا وافق.', 'We will notify you when they reply. Chat opens only after approval.'], ['ينتهي خلال 7 دقائق', 'Expires in 7 minutes'], ['إلغاء الطلب', 'Cancel request'], ['إلغاء العرض', 'Cancel offer'], ['تمام', 'Done'], ['ما تيسّر هالمرة. فيه أشخاص ثانيين حولك.', 'It did not work out this time. There are other people nearby.'], ['شوف غيره حولك', 'See others nearby'],
  ['الحين تقدرون تتواصلون وتنسقون اللقاء في', 'You can now message and coordinate your meeting at'], ['بعدين', 'Later'], ['خيارات', 'Options'], ['أنهِ المحادثة', 'End chat'], ['بلّغ عن مشكلة', 'Report a problem'], ['احظر', 'Block'], ['بلاغك سري، وما نقول له مين بلّغ.', 'Your report is private. We never reveal who submitted it.'], ['تصرف غير لائق', 'Inappropriate behaviour'], ['حساب مزيّف', 'Fake account'], ['رسائل مزعجة', 'Spam'], ['شي ثاني', 'Something else'], ['أرسل البلاغ', 'Submit report'],
  ['ليلى حسن', 'Layla Hassan'], ['عمر سعيد', 'Omar Saeed'], ['خالد منصور', 'Khaled Mansour'], ['رنا فارس', 'Rana Fares'], ['سارة الشمري', 'Sarah Alshammari'], ['طارق الجاسم', 'Tariq Aljassem'], ['فيصل العتيبي', 'Faisal Alotaibi'], ['نورة الدوسري', 'Noura Aldosari'], ['ريم السالم', 'Reem Alsalem'], ['يوسف العلي', 'Yousef Alali'], ['ماجد الحربي', 'Majed Alharbi'], ['هند القحطاني', 'Hind Alqahtani'], ['عبدالله الزهراني', 'Abdullah Alzahrani'], ['سامر خليلي', 'Samer Khalili'],
  ['مصممة جرافيك مستقلة', 'Freelance graphic designer'], ['مطور تطبيقات موبايل', 'Mobile app developer'], ['مختص تسويق رقمي', 'Digital marketing specialist'], ['صاحبة مشروع ناشئ', 'Startup founder'], ['محللة مالية ونمذجة', 'Financial modelling analyst'], ['مهندس حلول سحابية', 'Cloud solutions engineer'], ['صانع محتوى ومصور', 'Content creator and photographer'], ['كاتبة إعلانية ومترجمة', 'Copywriter and translator'], ['مطور واجهات أمامية', 'Front-end developer'],
  ['مراجعة الهوية والشعارات وتنسيق الواجهات وتجربة المستخدم', 'Brand identity, logo, interface, and user experience reviews'],
  ['حل مشاكل كود React Native واستكشاف أخطاء الدفع والربط', 'React Native debugging, payment issues, and integrations'],
  ['استشارات تسويقية وخطط إطلاق الحملات الإعلانية', 'Marketing advice and campaign launch planning'],
  ['تصوير المنتجات وجلسات سريعة بالجوال', 'Product photography and quick mobile photo sessions'],
  ['مراجعة نماذج Excel وحسابات التدفقات النقدية للمشاريع', 'Excel model and project cash-flow reviews'],
  ['استشارات معمارية الأنظمة السحابية وخوادم التطبيقات', 'Cloud architecture and application server advice'],
  ['أفكار محتوى ومراجعة حسابات التواصل الاجتماعي', 'Content ideas and social media account reviews'],
  ['مراجعة وتدقيق النصوص التسويقية وشعارات البراند', 'Marketing copy and brand tagline editing'],
  ['أحتاج رأي وملاحظات سريعة في تصميم تجربة واجهات تطبيق مشروعي', 'I need quick feedback on the interface and user experience of my app'],
  ['تطبيقي يعلّق ويظهر خطأ لما أفتح صفحة الدفع في Stripe', 'My app freezes and shows an error when I open the Stripe payment page'],
  ['واجهة تطبيقي ما تضبط على الجوالات ذات الشاشات الصغيرة وأحتاج مساعدة في CSS', 'My app layout breaks on small phones and I need help with CSS'],
  ['أبحث عن استشارة سريعة في تسعير اشتراكات تطبيق جديد موجه للشركات', 'I need quick advice on pricing subscriptions for a new B2B app'],
  ['مراجعة سريعة لشرائح العرض الاستثماري Pitch Deck قبل عرضه غداً', 'A quick review of my investor pitch deck before tomorrow'],
  ['أبغى أحد يراجع معي خطة إطلاق حملة إعلانية على سناب', 'I need someone to review my Snapchat campaign launch plan'],
  ['أصمم هويات بصرية للمشاريع الناشئة، وأحب أساعد في مراجعة الشعارات والعروض التقديمية.', 'I design brand identities for startups and enjoy reviewing logos and presentations.'],
  ['أطور تطبيقات React Native وTypeScript، وأقدر أساعد في حل مشاكل الكود واكتشاف الأخطاء بسرعة.', 'I build React Native and TypeScript apps and can help debug code quickly.'],
  ['أشتغل في التسويق الرقمي والإعلانات الممولة وحملات النمو للمتاجر الإلكترونية.', 'I work in digital marketing, paid ads, and growth campaigns for online stores.'],
  ['أبني مشروع ناشئ للمناسبات والهدايا، وأهتم جداً بتجربة العميل وجودة التفاصيل.', 'I am building an events and gifts startup and care deeply about customer experience.'],
  ['أساعد رواد الأعمال في بناء جداول التدفقات النقدية ودراسات الجدوى المالية لطلبات الاستثمار.', 'I help founders build cash-flow models and financial feasibility studies.'],
  ['أبني بنى تحتية سحابية وأنظمة Backend عالية الأداء للمنصات الرقمية.', 'I build cloud infrastructure and high-performance backend systems.'],
  ['أساعد أصحاب المشاريع في محتوى السوشال ميديا والتيك توك.', 'I help business owners with social media and TikTok content.'],
  ['شغوفة باللغة وصياغة رسائل البراندات والمقالات التسويقية.', 'I am passionate about language, brand messaging, and marketing articles.'],
  ['متاحة للمساعدة حتى 6:30 م', 'Available to help until 6:30 PM'], ['متاح للأسئلة البرمجية حتى 8:00 م', 'Available for coding questions until 8:00 PM'], ['متاح للاستشارات التسويقية من 4:30 إلى 7:00 م', 'Available for marketing advice from 4:30 to 7:00 PM'], ['متاحة لجلسات تصوير سريعة من 5:15 م', 'Available for quick photo sessions from 5:15 PM'], ['متاحة لمراجعة النماذج المالية حتى 5:00 م', 'Available to review financial models until 5:00 PM'], ['متاح لأسئلة السحابة والخوادم من 6:00 م', 'Available for cloud and server questions from 6:00 PM'], ['متاح لمراجعة الحسابات وأفكار المحتوى حتى المغرب', 'Available to review accounts and content ideas this evening'], ['متاحة لتدقيق النصوص من 5:45 م', 'Available for copy editing from 5:45 PM'],
  ['تصميم هوية بصرية', 'Brand identity design'], ['تطوير تطبيقات', 'App development'], ['حل أخطاء', 'Debugging'], ['تسويق رقمي', 'Digital marketing'], ['إعلانات تيك توك وسناب', 'TikTok and Snapchat ads'], ['حملات نمو', 'Growth campaigns'], ['تصوير منتجات', 'Product photography'], ['صناعة محتوى', 'Content creation'], ['تجربة مستخدم', 'User experience'], ['Excel ونمذجة', 'Excel and modelling'], ['مالية', 'Finance'], ['دراسات جدوى', 'Feasibility studies'], ['عروض استثمار', 'Investor decks'], ['هندسة سحابية', 'Cloud engineering'], ['محتوى تيك توك', 'TikTok content'], ['تصوير بالجوال', 'Mobile photography'], ['كتابة سيناريو', 'Script writing'], ['كتابة محتوى', 'Content writing'], ['كتابة إعلانية', 'Copywriting'], ['ترجمة', 'Translation'], ['صياغة نصوص', 'Editing'], ['تطوير واجهات', 'Front-end development'], ['عروض تقديمية', 'Presentations'], ['ذكاء اصطناعي', 'Artificial intelligence'], ['إدارة منتجات', 'Product management'], ['مراجعة عروض', 'Presentation review'], ['مراجعة كود', 'Code review'], ['استشارة تسويق', 'Marketing advice'], ['تسويق', 'Marketing'], ['تصميم', 'Design'], ['تطبيقات', 'Apps'], ['دفع إلكتروني', 'Payments'], ['كود', 'Code'], ['تسعير واستراتيجية', 'Pricing and strategy'], ['تسعير', 'Pricing'], ['استثمار', 'Investment'], ['إعلانات', 'Advertising'], ['سناب', 'Snapchat'],
  ['موجودة الحين، وتطلع من الكافيه بعد', 'Here now, leaves the coffee shop in'], ['موجود الحين، ويطلع من الكافيه بعد', 'Here now, leaves the coffee shop in'], ['موجودة الحين، وطلعت من الكافيه', 'Left the coffee shop'], ['موجود الحين، وطلع من الكافيه', 'Left the coffee shop'],
  ['تطلع من الكافيه الساعة', 'Leaves the coffee shop at'], ['يطلع من الكافيه الساعة', 'Leaves the coffee shop at'], ['توصل الكافيه بعد', 'Arrives at the coffee shop in'], ['يوصل الكافيه بعد', 'Arrives at the coffee shop in'], ['وصلت الكافيه', 'Arrived at the coffee shop'], ['وصل الكافيه', 'Arrived at the coffee shop'],
  ['ابحث عن كافيه أو حي', 'Search coffee shops or neighbourhoods'], ['نوع الأشخاص حولك', 'Who is nearby'], ['تصميم تطبيق', 'App design'], ['الأنسب', 'Best match'], ['الأقرب', 'Nearest'], ['الموقع:', 'Location:'], ['تغيير', 'Change'], ['بحث', 'Search'],
  ['مغادرة بعد:', 'Leaves in:'], ['وصول بعد:', 'Arrives in:'], ['توصل', 'Arrives'], ['الساعة', 'at'],
  ['ما لقينا أحد بهالخيارات', 'No one matches these options'], ['جرّب «الكل» أو كلمة بحث ثانية.', 'Try "All" or a different search.'], ['ما لقينا كافيه بهالخيارات', 'No coffee shops match these options'], ['جرّب اسم الحي بدل اسم الكافيه.', 'Try the neighbourhood instead of the coffee shop name.'], ['جرّب فلتر ثاني.', 'Try a different filter.'], ['اعرض الكل', 'Show all'],
  ['ابحث بالمهارة أو التخصص', 'Search by skill or field'], ['ابحث بنوع الاحتياج', 'Search by type of request'], ['إغلاق البحث', 'Close search'], ['إلغاء الحفظ', 'Unsave'], ['حفظ الكافيه', 'Save coffee shop'], ['عن المكان', 'About the place'],
  ['حالياً متاح في', 'Currently available in'], ['ما وصلنا', 'Not yet in'], ['للحين', ''], ['ويظهر لك نفس الجنس فقط حسب تفضيلك.', 'Only the same gender is shown based on your preference.'],
  ['بيشوف طلبك بدون اسمك وصورتك، ويظهرون بعد الموافقة', 'will see your request without your name and photo until approval'], ['بتشوف طلبك بدون اسمك وصورتك، ويظهرون بعد الموافقة', 'will see your request without your name and photo until approval'], ['بيشوف اسمك وصورتك مع الطلب', 'will see your name and photo with the request'], ['بتشوف اسمك وصورتك مع الطلب', 'will see your name and photo with the request'],
  ['كم تحتاج من وقته تقريبًا؟', 'About how much of his time do you need?'], ['كم تحتاج من وقتها تقريبًا؟', 'About how much of her time do you need?'], ['تطلب مساعدة', 'Ask for help from'], ['إلى صاحب الاحتياج', 'To the person who needs help'], ['إلى', 'To'],
  ['نعرض لك الأقرب من', 'Showing the closest to'], ['اخترت', 'You chose'], ['ألغينا طلبك', 'Request cancelled'], ['ألغينا عرضك', 'Offer cancelled'], ['ألغينا الطلب', 'Request cancelled'], ['ألغينا العرض', 'Offer cancelled'],
  ['نتمنى إنه كان لقاء مفيد', 'We hope it was a useful meeting'], ['حظرت هذا الشخص', 'You blocked this person'], ['حظرت', 'You blocked'], ['أنهيت المحادثة', 'You ended the chat'], ['حفظنا مهاراتك واحتياجاتك', 'Saved your skills and needs'], ['حفظنا التعديلات', 'Changes saved'], ['وصلنا بلاغك، وبنراجعه بأسرع وقت', 'We got your report and will review it soon'], ['حفظنا الكافيه في حسابك', 'Coffee shop saved to your account'], ['شلنا الكافيه من المحفوظة', 'Removed from saved coffee shops'],
  ['تقابلتوا. نتمنى إنه كان لقاء مفيد', 'You met. We hope it was useful'], ['ما تقابلتوا بعد. كمّلوا التنسيق هنا', 'You have not met yet. Keep coordinating here'], ['انتهت المحادثة', 'Chat ended'], ['تقابلتوا', 'You met'], ['اتفقتوا 🤝', 'Agreed 🤝'],
  ['هلا، شكرًا إنك وافقت تساعدني! أنا', 'Hi, thanks for agreeing to help! I am'], ['هلا، أقدر أساعدك في', 'Hi, I can help you with'], ['تعال متى ما جهزت 👋', 'come over whenever you are ready 👋'], ['هلا!', 'Hi!'], ['أوصل', 'I arrive at'], ['وأكون', 'and will be'], ['أنا', 'I am'], ['ولا يهمك، أنتظرك', 'No problem, I will wait'], ['تمام، أنتظرك', 'Great, I will wait for you'], ['أحتاج مساعدة في', 'I need help with'],
  ['مراجعة تصميم وهوية', 'Design and brand review'], ['مراجعة عرض تقديمي', 'Presentation review'], ['Excel ونماذج مالية', 'Excel and financial models'], ['Excel ومالية', 'Excel and finance'], ['كتابة وتدقيق نصوص', 'Writing and proofreading'], ['تطوير تطبيق', 'App development'], ['مراجعة عرض', 'Presentation review'], ['بايثون', 'Python'], ['برمجة', 'Programming'], ['تصوير', 'Photography'], ['هوية', 'Branding'], ['شعار', 'Logo'], ['تطبيق', 'App'],
  ['أبني مشروع ناشئ وأحتاج مشورة في معمارية التطبيق وقاعدة البيانات.', 'I am building a startup and need advice on app architecture and the database.'],
  ['أقدر أساعد في', 'I can help with'], ['مجالات', 'areas'],
  ['حفظ', 'Save'], ['رجوع', 'Back'], ['خيارات', 'Options'], ['حذف', 'Remove'], ['قريب منك', 'Near you'], ['منك', 'away'], ['متاح في', 'available in'], ['حاليًا', 'currently'], ['بس.', 'only.'], ['نبلغك أول ما نوصل مدينتك.', 'We will notify you when we launch in your city.'], ['لسا ما وصل', 'is not available in'], ['نفس الجنس فقط حسب تفضيلك.', 'Only the same gender is shown based on your preference.'], ['الاحتياجات تظهر بدون اسم أو صورة حتى الموافقة.', 'Requests stay anonymous until approval.'], ['يحتاج', 'Needs'], ['يوصل', 'Arrives'], ['الجلسة:', 'Seat:'], ['وقت التواجد', 'Availability'], ['نبذة', 'About'], ['يقدر يساعدك في', 'Can help you with'], ['تقدر تساعدك في', 'Can help you with'], ['الأنسب لـ:', 'Best matches for:'], ['حسب مهاراتك:', 'Based on your skills:'], ['إعادة التجربة من شاشة البداية', 'Restart from onboarding'], ['إعادة تعيين التجربة', 'Reset demo'], ['وضع العرض', 'Display mode'], ['محاكي الجوال', 'Phone preview'], ['العرض الموسع', 'Wide preview'],
]

const arabic = /[\u0600-\u06ff]/

// Short presence words that only appear on their own, so they are matched whole rather than inside other words.
const EXACT: Record<string, string> = { 'طلع': 'Left', 'طلعت': 'Left', 'وصل': 'Arrived', 'وصلت': 'Arrived', 'وقته خلص': 'Time is up', 'أقل من دقيقة': 'under 1 min', 'مهارة': '1 skill', 'مهارتين': '2 skills', 'مجال': '1 area', 'مجالين': '2 areas' }

export function toEnglish(value: string): string {
  if (!arabic.test(value)) return value
  if (EXACT[value.trim()]) return value.replace(value.trim(), EXACT[value.trim()])
  let result = value
    .replace(/(\d+) حولك يقدرون يساعدون الآن/g, '$1 people nearby can help now')
    .replace(/(\d+) احتياجات حولك اليوم/g, '$1 nearby requests today')
    .replace(/(\d+) من (\d+) مهارات/g, '$1 of $2 skills')
  for (const [source, target] of [...EN].sort((a, b) => b[0].length - a[0].length)) result = result.split(source).join(target)
  // Countdown durations: «ساعتين و30 دقيقة» → «2 h 30 min» (minutes are already «min» from the list above).
  result = result
    .replace(/ساعتين/g, '2 h').replace(/دقيقتين/g, '2 min')
    .replace(/(\d+) (?:ساعات|ساعة)/g, '$1 h').replace(/ساعة/g, '1 h')
    .replace(/(h) و(\d)/g, '$1 $2')
  result = result
    .replace(/(\d{1,2}:\d{2}) م/g, '$1 PM')
    .replace(/(\d{1,2}:\d{2}) ص/g, '$1 AM')
    .replace(/(\d+(?:\.\d+)?) كم/g, '$1 km')
    .replace(/(\d+) م(?=\s|$|·)/g, '$1 m')
  result = result.replaceAll('،', ',')
  // Copy without a translation, and anything people type themselves, stays as written rather than being hidden.
  return result
}

export const englishCafeName = (name: string) => toEnglish(name)
